apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-sample-app
  namespace: ac-sample-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: public.ecr.aws/nginx/nginx:1.21
          ports:
            - name: tcp
              containerPort: 80
          resources:
            limits:
              memory: 2Gi
              cpu: "1"
            requests:
              memory: 2Gi
              cpu: "1"
