apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-test
  namespace: hpa-test
spec:
  replicas: 10
  selector:
    matchLabels:
      run: hpa-test
  template:
    metadata:
      labels:
        run: hpa-test
        developer: daichiwei
    spec:
      containers:
        - name: hpa-test
          image: <i am a test image>
          resources:
            limits:
              memory: 4Gi
              cpu: "2"
            requests:
              memory: 2Gi
              cpu: "1"
          env:
            - name: ENV
              value: test
